dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='index'),

    # git-pull
    path('git-pull', views.GitPullView.as_view(), name='git-pull'),

    # audit-trail
    path('audits', views.AuditTrailListView.as_view(), name='audittrail-list'),

    # accounts
    path('accounts/signup/', views.SignupView.as_view(), name='signup'),
    path('accounts/login/', views.LoginPageView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/change-password/',
         views.ChangePasswordView.as_view(), name='change-password'),

    # designation crud
    path('designations/', views.DesignationListView.as_view(),
         name='designations-list'),
    path('designations/create', views.DesignationCreateView.as_view(),
         name='designations-create'),
    path('designations/<int:pk>/update',
         views.DesignationUpdateView.as_view(), name='designations-update'),
    path('designations/<int:pk>/delete',
         views.DesignationDeleteView.as_view(), name='designations-delete'),

    # grouprequiredmixin test
    path('groups/', views.GroupRequiredTestView.as_view(), name='groups-list'),


    # user crud
    path('users/', views.UserListView.as_view(), name='users-list'),
    path('users/create', views.UserCreateView.as_view(), name='users-create'),
    path('users/<int:pk>/update',
         views.UserUpdateView.as_view(), name='users-update'),
    path('users/<int:pk>/status',
         views.UserStatusView.as_view(), name='users-status'),
    path('users/<int:pk>/password-reset',
         views.UserPasswordResetView.as_view(), name='users-password-reset'),

     #seller crud
     path('pending/seller', views.PendingSellerListView.as_view(), name ='pending-seller'),
     path('accept/<int:seller_pk>/seller', views.AcceptSellerView.as_view(), name ='accept-seller'),

     path('active/seller', views.ActiveSellerListView.as_view(), name ='active-seller'),
     path('block/<int:seller_pk>/seller', views.BlockSellerView.as_view(), name ='block-seller'),

     path('blocked/seller', views.BlockedSellerListView.as_view(), name ='blocked-seller'),
     path('reactivate/<int:seller_pk>/seller', views.ReActivateSellerView.as_view(), name ='re-activate-seller'),
     path('delete/<int:pk>/seller', views.SellerDeleteView.as_view(), name ='delete-seller'),


]

ecomapp/urls.py
from django.urls import path
from .views import *

app_name ="ecomapp"

urlpatterns =[
		path('', HomeView.as_view(), name="home"),
		path('about/', AboutView.as_view(), name="about"),
        path("contact/", ContactView.as_view(), name="contact"),
		path('all-products/', AllProductsView.as_view(), name="allproducts"),
		path('product-detail-<slug:slug>/', ProductDetailView.as_view(), name="product-detail"),

		path('add-to-cart/<int:pro_id>/', AddToCartView.as_view(), name='addtocart'),
		path('my-cart/', MycartView.as_view(), name="mycart"),
		path('manage-cart/<int:cp_id>/', ManageCartView.as_view(), name='namagecart'),
		path('empty-cart/', EmptyCartView.as_view(), name='emptycart'),
		path('check-out/', CheckOutView.as_view(), name='checkout'),
		path('khalti-request/', KhaltiRequestView.as_view(), name='khaltirequest'),
		path('customer-registration/', CustomerRegistrationView.as_view(), name="customerregistration"),
    	path("user-name-checker/", UserNameCheckerView.as_view(), name="usernamechecker"),
    	path("customer-logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    	path("customer-login/", CustomerLoginView.as_view(), name="customerlogin"),
    	path("c-login/", CutomLoginView.as_view(), name="c-login"),
    	path("customer-profile/", CustomerProfileView.as_view(), name="customerprofile"),
    	path("customer-order-detail-<int:pk>/", CustomerOrderDetailView.as_view(), name="customerorderdetail"),
    	path("serch/", SearchView.as_view(), name="search"),
        path("forgot-password/", ForgotPasswordView.as_view(), name="forgot_password"),
        path("password-reset/<email>/<token>/", PasswordResetView.as_view(), name="password_reset"),
        path("product/<slug:slug>/lists/", CategorisedProductView.as_view(), name="product_by_cat"),

    	#admin
    	path("admin-dashboard/", AdminHomeView.as_view(), name="adminhome"),
    	path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
		path("logout", LogoutView.as_view(), name="logout"),
    	path("admin-dashboard/pending-orders/", AdminPendingOrderView.as_view(), name="amdin_pending_orders"),
    	path("admin-dashboard/order-<int:pk>/", AdminOrderDetailView.as_view(), name="admin_order_detail"),
        path("admin-dashboard/orderlist/", AdminOrderListView.as_view(), name="amdin_orderlist"),
    	path("admin-dashboard/orderlist-<slug:slug>/", AdminOrderByStatusView.as_view(), name="amdin_order_by_status"),
        path("admin-dashboard/order-status-<int:pk>/", AdminOrderStatusChangeView.as_view(), name="admin_order_status_change"),
    	path("admin-dashboard/product-list/", AdminProductListView.as_view(), name="admin_product_list"),
        path("admin-dashboard/product-detail-<int:pk>/", AdminProductDetailView.as_view(), name="admin_product_detail"),
    	path("admin-dashboard/product-create/", AdminProductCreateView.as_view(), name="admin_product_create"),
		path("admin-dashboard/product-update-<int:pk>/", AdminProductUpdateView.as_view(), name="admin_product_update"),
		path("admin-dashboard/product-delete-<int:pk>/", AdminProductDeleteView.as_view(), name="admin_product_delete"),

		# multiple image url 
		path("multiple/image/", MultipleImageCreateView.as_view(),name="multipleimage"),

		#Review url
		path("product/<int:product_pk>/review/", ProductReview.as_view(), name="product-review"),





]

dashboard/views.py
import subprocess
import geocoder

from django.utils.crypto import get_random_string
from django.contrib.auth.hashers import make_password

from django.conf import settings as conf_settings
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash, get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import query
from django.http import HttpResponse, request
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import resolve, reverse, reverse_lazy
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.views.generic import View, TemplateView, FormView, ListView, CreateView, UpdateView, DeleteView, DetailView

from .forms import (
	ChangePasswordForm,
	LoginForm,
	SignUpForm,
	DesignationForm,
	UserForm
)
from .mixins import (
	BaseMixin,

	CustomLoginRequiredMixin,
	GetDeleteMixin,
	GroupRequiredMixin,
	NonDeletedListMixin,
	NonLoginRequiredMixin,
	NonSuperAdminRequiredMixin,
	SuperAdminRequiredMixin,
	UserRelatedListMixin
)
from audit.mixins import AuditCreateMixin, AuditDeleteMixin, AuditUpdateMixin
from audit.models import AuditTrail
from .models import Designation
from audit.utils import store_audit

from ecomapp.models import (
	Admin
)

User = get_user_model()


class HomeView(View):
	def get(self, request, *args, **kwargs):
		return redirect('dashboard:login')


class DashboardView(CustomLoginRequiredMixin,  BaseMixin, TemplateView):
	template_name = 'dashboard/index.html'


# Git Pull View
class GitPullView(CustomLoginRequiredMixin, SuperAdminRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		process = subprocess.Popen(
			['./pull.sh'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
		returncode = process.wait()
		output = ''
		output += process.stdout.read().decode("utf-8")
		output += '\nReturned with status {0}'.format(returncode)
		response = HttpResponse(output)
		response['Content-Type'] = 'text'
		return response

# Registration


class SignupView(BaseMixin, NonLoginRequiredMixin, CreateView):
	form_class = SignUpForm
	success_url = reverse_lazy('dashboard:index')
	template_name = 'dashboard/auth/signup.html'

	def form_valid(self, form):
		# saving user
		user = User.objects.create(
			username=form.cleaned_data.get('username'),
			first_name=form.cleaned_data.get('first_name'),
			last_name=form.cleaned_data.get('last_name'),
			email=form.cleaned_data.get('username')
		)
		user.set_password(form.cleaned_data.get('password'))
		user.save()

		# logging in user after registration
		login(self.request, user)
		return redirect(self.success_url)

	def form_invalid(self, form):
		if self.request.is_ajax():
			return JsonResponse({'errors': form.errors}, status=400)
		return super().form_invalid(form)


# Login Logout Views
class LoginPageView(NonLoginRequiredMixin, FormView):
	form_class = LoginForm
	template_name = "dashboard/auth/login.html"

	def form_valid(self, form):
		username = form.cleaned_data.get('username')
		password = form.cleaned_data.get('password')
		user = authenticate(username=username, password=password)

		# Remember me
		if self.request.POST.get('remember', None) == None:
			self.request.session.set_expiry(0)

		login(self.request, user)
		store_audit(request=self.request,
					instance=self.request.user, action='LOGIN')

		if 'next' in self.request.GET:
			return redirect(self.request.GET.get('next'))
		return redirect('dashboard:index')


class LogoutView(CustomLoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		store_audit(request=self.request,
					instance=self.request.user, action='LOGOUT')
		logout(request)
		return redirect('dashboard:login')

# Password Reset


class ChangePasswordView(CustomLoginRequiredMixin, SuccessMessageMixin, FormView):
	form_class = ChangePasswordForm
	template_name = "dashboard/auth/change_password.html"
	success_message = "Password Has Been Changed"
	success_url = reverse_lazy('dashboard:index')

	def get_form(self):
		form = super().get_form()
		form.set_user(self.request.user)
		return form

	def form_valid(self, form):
		account = User.objects.filter(username=self.request.user).first()
		account.set_password(form.cleaned_data.get('confirm_password'))
		account.save(update_fields=['password'])
		user = authenticate(username=self.request.user,
							password=form.cleaned_data.get('confirm_password'))
		login(self.request, user)
		return super().form_valid(form)


# Designation CRUD
class DesignationListView(CustomLoginRequiredMixin, NonDeletedListMixin, ListView):
	model = Designation
	template_name = "dashboard/designations/list.html"
	paginate_by = 100

	def get_queryset(self):
		return super().get_queryset().order_by('-created_at')


class DesignationCreateView(CustomLoginRequiredMixin, SuccessMessageMixin, AuditCreateMixin, CreateView):
	form_class = DesignationForm
	success_message = "Designation Created Successfully"
	success_url = reverse_lazy('dashboard:designations-list')
	template_name = "dashboard/designations/form.html"


class DesignationUpdateView(CustomLoginRequiredMixin, NonDeletedListMixin, SuccessMessageMixin, AuditUpdateMixin, UpdateView):
	form_class = DesignationForm
	model = Designation
	success_message = "Designation Updated Successfully"
	success_url = reverse_lazy('dashboard:designations-list')
	template_name = "dashboard/designations/form.html"


class DesignationDeleteView(CustomLoginRequiredMixin, SuccessMessageMixin, GetDeleteMixin, AuditDeleteMixin, DeleteView):
	model = Designation
	success_message = "Designation Deleted Successfully"
	success_url = reverse_lazy('dashboard:designations-list')


# User CRUD
class UserListView(CustomLoginRequiredMixin, SuperAdminRequiredMixin, ListView):
	model = User
	template_name = "dashboard/users/list.html"
	paginate_by = 100

	def get_queryset(self):
		return super().get_queryset().exclude(username=self.request.user)


class UserCreateView(CustomLoginRequiredMixin, SuperAdminRequiredMixin, SuccessMessageMixin, AuditCreateMixin, CreateView):
	form_class = UserForm
	success_message = "User Created Successfully"
	success_url = reverse_lazy('dashboard:users-list')
	template_name = "dashboard/users/form.html"

	def get_success_url(self):
		return reverse('dashboard:users-password-reset', kwargs={'pk': self.object.pk})


class UserUpdateView(CustomLoginRequiredMixin, SuperAdminRequiredMixin, SuccessMessageMixin, AuditUpdateMixin, UpdateView):
	form_class = UserForm
	model = User
	success_message = "User Updated Successfully"
	success_url = reverse_lazy('dashboard:users-list')
	template_name = "dashboard/users/form.html"


class UserStatusView(CustomLoginRequiredMixin, SuperAdminRequiredMixin, SuccessMessageMixin, View):
	model = User
	success_message = "User's Status Has Been Changed"
	success_url = reverse_lazy('dashboard:users-list')

	def get(self, request, *args, **kwargs):
		user_id = self.kwargs.get('pk')
		if user_id:
			account = User.objects.filter(pk=user_id).first()
			if account.is_active == True:
				account.is_active = False
			else:
				account.is_active = True
			account.save(update_fields=['is_active'])
		return redirect(self.success_url)


# Password Reset
class UserPasswordResetView(CustomLoginRequiredMixin, SuperAdminRequiredMixin, SuccessMessageMixin, View):
	model = User
	success_url = reverse_lazy("dashboard:users-list")
	success_message = "Password has been sent to the user's email."

	def get(self, request, *args, **kwargs):
		user_pk = self.kwargs.get('pk')
		account = User.objects.filter(pk=user_pk).first()
		password = get_random_string(length=6)
		account.set_password(password)
		msg = (
			"You can login into the Dashboard with the following credentials.\n\n" +
			"Username: " + account.username + " \n" + "Password: " + password
		)
		send_mail("Dashboard Credentials", msg, conf_settings.EMAIL_HOST_USER, [
				  account.email], fail_silently=True)
		account.save(update_fields=["password"])

		messages.success(self.request, self.success_message)
		return redirect(self.success_url)


# GroupRequiredMixinTest
class GroupRequiredTestView(CustomLoginRequiredMixin, GroupRequiredMixin, TemplateView):
	template_name = "dashboard/designations/list.html"
	group_required = ['editor']


# AuditTrail List
class AuditTrailListView(CustomLoginRequiredMixin, SuperAdminRequiredMixin, ListView):
	model = AuditTrail
	paginate_by = 100
	template_name = 'dashboard/audittrails/list.html'

	def get_queryset(self):
		queryset = super().get_queryset()
		return queryset.order_by('-created_at')

# seller crud
class PendingSellerListView(CustomLoginRequiredMixin, ListView):
	model = Admin
	paginate_by = 20
	template_name = 'dashboard/seller/pending-list.html'

	def get_queryset(self):
		return super().get_queryset().filter(status='Pending')


class AcceptSellerView(CustomLoginRequiredMixin, SuccessMessageMixin, View):
	
	def get_seller(self):
		if not hasattr(self, 'seller'):
			self.seller = get_object_or_404(Admin, pk=self.kwargs.get('seller_pk'))
		return self.seller

	def get(self, *args, **kwargs):
		seller = self.get_seller()
		if seller.status == 'Pending':
			seller.status = 'Accepted'
			seller.save(update_fields=['status'])
		#get customer and then user
		password = get_random_string(8)
		user = User.objects.filter(username=seller.email).first()
		user.set_password(password)
		user.save(update_fields=['password'])

		text_content = '''You are now official sajilo bazar seller.
		username: {}
		password: {}'''.format(seller.email, password)
		send_mail(

dashboard/templates/dashboard/users/form.html
{% extends "dashboard/base/index.html" %}

{% load static %}

{% block title %} User {% endblock %}

{% block content %}
<div class="container-fluid page__container">
    <div class="card card-form form-header-layout">
        <h1 style="padding: 27px !important;"> User </h1>
        <div class="row no-gutters" style="border-top: 1px solid #EFEFEF">
            <div class="col-lg-12 card-form__body card-body pomelo-form-caard" style="background:none !important;">
                <form method="post" action="" enctype="multipart/form-data" autocomplete="off">
                    
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group" >
                        <label>{{ field.label }}{% if field.field.required %}* {% endif %}</label>
                        {{ field }}
                        <span style="color:red;">{{ field.errors|striptags|safe }}</span>
                    </div>
                    {% endfor %}    

                    <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}


dashboard/templates/dashboard/users/list.html
{% extends "dashboard/base/index.html" %}

{% load static %}

{% block title %} Users {% endblock %}

{% block subtitle %} Users {% endblock %}

{% block content %}

<div class="container-fluid page__container">
    <div class="card document-card">
        <div class="row mb-4 mt-4 mr-2">
            <div class="col-md-12">
                <div style="text-align: right">
                    <a href="{% url 'dashboard:users-create' %}" class="btn btn-outline-primary">
                        <i class="fa fa-plus"></i>&nbsp; Add User
                    </a>
                </div>
            </div>
        </div>
        <div class="row ml-2 mr-2 mb-2 mt-2">
            <div class="col-sm-12 document-table-space">
                <table class="table  w-full no-footer" role="grid">
                    <thead class="table-space-top-bottom">
                        <tr role="row">
                            <th>S.N</th>
                            <th>Name</th>
                            <th>Group</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for users in object_list %}
                        <tr>
                            <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                            <td>{{ users.username }}</td>
                            <td><span class="badge badge-secondary">{{ users.groups.all.0 }}</span></td>
                            <td>{{ users.email }}</td>
                            <td>{% if users.is_active == True %} <span class="badge badge-success"> Active </span> {% else %} <span class="badge badge-danger"> In Active </span> {% endif %}</td>
                            <td>
                                <div class="btn-group" role="group" style="margin:auto;">
                                    <a href="{% url 'dashboard:users-password-reset' users.id %}"
                                        class=" btn-success password-reset">
                                        <button type="button" class="btn-sm btn btn-primary">Reset Password</button>
                                    </a>
                                    &nbsp;
                                    <a href="{% url 'dashboard:users-update' users.id %}" class="btn-sm btn btn-info btn-success-space" data-toggle="tooltip" data-original-title='Modify'>
                                        <i class="fa fa-pencil-alt"></i>
                                    </a>
                                    {% if request.user.is_superuser %}
                                    <a href="{% url 'dashboard:users-status' users.id %}" data-toggle="tooltip"  {% if users.is_active == True %} class="btn-sm btn btn-danger user-deactivate" data-original-title='Deactivate'  {% else %} class="btn-sm btn btn-success user-activate" data-original-title='Activate' {% endif %}>
                                        {% if users.is_active == True %}
                                        <i class="fas fa-ban"></i>
                                        {% else %}
                                        <i class="fas fa-check"></i>
                                        {% endif %}
                                    </a>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
                {% include 'dashboard/base/pagination.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
// password reset link
    $('body').on('click', '.password-reset', function (e) {
        e.preventDefault();
        Swal.fire({
            title: 'Are you sure?',
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Password Reset It!'
        }).then((result) => {
            if (result.value) {
                window.location.href = $(this).attr('href');
            }
        })
    });

// user activate 
$('body').on('click', '.user-activate', function (e) {
    e.preventDefault();
    Swal.fire({
        title: 'Are you sure you want to activate this user?',
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Activate It!'
    }).then((result) => {
        if (result.value) {
            window.location.href = $(this).attr('href');
        }
    })
});

// user deactivate 
$('body').on('click', '.user-deactivate', function (e) {
    e.preventDefault();
    Swal.fire({
        title: 'Are you sure you want to deactivate this user?',
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Deactivate It!'
    }).then((result) => {
        if (result.value) {
            window.location.href = $(this).attr('href');
        }
    })
});
</script>
{% endblock %}