ecomapp/urls.py
from django.urls import path
from .views import *

app_name ="ecomapp"

urlpatterns =[
		path('', HomeView.as_view(), name="home"),
		path('about/', AboutView.as_view(), name="about"),
        path("contact/", ContactView.as_view(), name="contact"),
		path('all-products/', AllProductsView.as_view(), name="allproducts"),
		path('product-detail-<slug:slug>/', ProductDetailView.as_view(), name="product-detail"),

		path('add-to-cart/<int:pro_id>/', AddToCartView.as_view(), name='addtocart'),
		path('my-cart/', MycartView.as_view(), name="mycart"),
		path('manage-cart/<int:cp_id>/', ManageCartView.as_view(), name='namagecart'),
		path('empty-cart/', EmptyCartView.as_view(), name='emptycart'),
		path('check-out/', CheckOutView.as_view(), name='checkout'),
		path('khalti-request/', KhaltiRequestView.as_view(), name='khaltirequest'),
		path('customer-registration/', CustomerRegistrationView.as_view(), name="customerregistration"),
    	path("user-name-checker/", UserNameCheckerView.as_view(), name="usernamechecker"),
    	path("customer-logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    	path("customer-login/", CustomerLoginView.as_view(), name="customerlogin"),
    	path("c-login/", CutomLoginView.as_view(), name="c-login"),
    	path("customer-profile/", CustomerProfileView.as_view(), name="customerprofile"),
    	path("customer-order-detail-<int:pk>/", CustomerOrderDetailView.as_view(), name="customerorderdetail"),
    	path("serch/", SearchView.as_view(), name="search"),
        path("forgot-password/", ForgotPasswordView.as_view(), name="forgot_password"),
        path("password-reset/<email>/<token>/", PasswordResetView.as_view(), name="password_reset"),
        path("product/<slug:slug>/lists/", CategorisedProductView.as_view(), name="product_by_cat"),

    	#admin
    	path("admin-dashboard/", AdminHomeView.as_view(), name="adminhome"),
    	path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
		path("logout", LogoutView.as_view(), name="logout"),
    	path("admin-dashboard/pending-orders/", AdminPendingOrderView.as_view(), name="amdin_pending_orders"),
    	path("admin-dashboard/order-<int:pk>/", AdminOrderDetailView.as_view(), name="admin_order_detail"),
        path("admin-dashboard/orderlist/", AdminOrderListView.as_view(), name="amdin_orderlist"),
    	path("admin-dashboard/orderlist-<slug:slug>/", AdminOrderByStatusView.as_view(), name="amdin_order_by_status"),
        path("admin-dashboard/order-status-<int:pk>/", AdminOrderStatusChangeView.as_view(), name="admin_order_status_change"),
    	path("admin-dashboard/product-list/", AdminProductListView.as_view(), name="admin_product_list"),
        path("admin-dashboard/product-detail-<int:pk>/", AdminProductDetailView.as_view(), name="admin_product_detail"),
    	path("admin-dashboard/product-create/", AdminProductCreateView.as_view(), name="admin_product_create"),
		path("admin-dashboard/product-update-<int:pk>/", AdminProductUpdateView.as_view(), name="admin_product_update"),
		path("admin-dashboard/product-delete-<int:pk>/", AdminProductDeleteView.as_view(), name="admin_product_delete"),

		# multiple image url 
		path("multiple/image/", MultipleImageCreateView.as_view(),name="multipleimage"),

		#Review url
		path("product/<int:product_pk>/review/", ProductReview.as_view(), name="product-review"),





]

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User,Group
from PIL import Image
from django.db.models.fields import related_descriptors
from django.utils import timezone
from ckeditor.fields import RichTextField

class DateTimeModel(models.Model):
	created_at = models.DateTimeField(
		auto_now_add=True,
		auto_now=False,
	)
	updated_at = models.DateTimeField(
		auto_now_add=False,
		auto_now=True,
	)
	deleted_at = models.DateTimeField(null=True, blank=True)

	class Meta:
		abstract = True

	def delete(self, hard=False):
		if not hard:
			self.deleted_at = timezone.now()
			super().save()
		else:
			super().delete()

SELER_STATUS = (
	('Accepted','Accepted'),
	('Pending', 'Pending'),
	('Blocked', 'Blocked')
)

class Images(models.Model):
	image = models.ImageField(upload_to = 'images')

	class Meta:
		verbose_name = ("Image")
		verbose_name_plural = ("Images")

class Admin(DateTimeModel, User):
	middle_name 	= models.CharField(max_length=200, null=True, blank=True)
	address 	= models.CharField(max_length=300)
	image 		= models.ImageField(upload_to='admin')
	mobile		= models.CharField(max_length=10)
	location = models.CharField(max_length=50)
	status = models.CharField(max_length=50, default="Pending", choices=SELER_STATUS)
	is_seller = models.BooleanField(default=True)

	def save(self, *args, **kwargs):
		self.username = self.email
		return super().save(*args, **kwargs)
		

	def __str__(self):
		return self.username


class Customer(DateTimeModel):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	full_name 	= models.CharField(max_length=200)
	address 	= models.CharField(max_length=300, null=True, blank=True)
	mobile = models.CharField(max_length=10)
	is_customer = models.BooleanField(default=True)


	def __str__(self):
		return self.mobile

class Category(DateTimeModel):
	title 	= models.CharField(max_length=300)
	parent = models.ForeignKey('self', related_name='sub_category', on_delete=models.CASCADE, null=True, blank=True)
	slug 	= models.SlugField(unique=True)

	def __str__(self):
		full_path=[self.title]
		k=self.parent
		while k is not None:
			full_path.append(k.title)
			k = k.parent
		return '->'.join(full_path[::-1])



class Product(DateTimeModel):
	seller 		= models.ForeignKey(Admin, on_delete=models.CASCADE)
	title 		= models.CharField(max_length=300)
	slug 		= models.SlugField(unique=True)
	category 	= models.ForeignKey(Category, on_delete = models.CASCADE)
	image 		= models.ManyToManyField(Images)
	marked_price= models.PositiveIntegerField()
	selling_price=models.PositiveIntegerField()
	description = RichTextField()
	warranty 	= models.CharField(max_length=400, null=True, blank=True)
	return_policy=models.CharField(max_length=300, null=True, blank=True)
	view_count 	= models.PositiveIntegerField(default=0)


	def __str__(self):
		return self.title


class Cart(DateTimeModel):
	customer 	= models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
	total 		= models.PositiveIntegerField(default=0)
	created_at 	= models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "Cart: " + str(self.id)

class CartProduct(DateTimeModel):
	cart 	= models.ForeignKey(Cart, on_delete = models.CASCADE)
	product = models.ForeignKey(Product, on_delete = models.CASCADE)
	rate 	= models.PositiveIntegerField()
	quantity= models.PositiveIntegerField()
	subtotal= models.PositiveIntegerField()

	def __str__(self):
		return "Cart: " + str(self.cart.id) + "   CartProduct: " + str(self.id)


ORDER_STATUS = (
	('Order Received', 'Order Received'),
	('Order Processing', 'Order Processing'),
	('On the way','On the way'),
	('Order Completed', 'Order Completed'),
	('Order Canceled', 'Order Canceled'),
	)

METHOD = {
	("Cash On Delivery", "Cash On Delivery"),
	("Khalti", "Khalti"),
}



class Order(DateTimeModel):
	cart 			= models.OneToOneField(Cart, on_delete=models.CASCADE)
	ordered_by		= models.CharField(max_length=300)
	shipping_address= models.CharField(max_length=200)
	mobile 			= models.CharField(max_length=10)
	email 			= models.EmailField(null=True)
	subtotal		= models.PositiveIntegerField()
	discount 		= models.PositiveIntegerField()
	total			= models.PositiveIntegerField()
	order_status	= models.CharField(max_length=50, choices=ORDER_STATUS)
	created_at		= models.DateTimeField(auto_now_add=True)
	payment_method = models.CharField(
		max_length=20, choices=METHOD, default="Cash On Delivery")
	payment_completed = models.BooleanField(
		default=False, null=True, blank=True) 
	
	def __str__(self):
		return "Order: " + str(self.id)



class Review(DateTimeModel):
	user = models.ForeignKey(Customer, on_delete= models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
	rate = models.PositiveIntegerField(default=0)
	description = models.TextField()

	def __str__(self):
		return self.product.title
	

templates/addtocart.html
{% comment %} {% extends 'base.html' %}
{% load static %}
{% block main %}
	<!-- banner-2 -->
	<div class="page-head_agile_info_w3l">

	</div>
	<!-- //banner-2 -->
	<!-- page -->
	<div class="services-breadcrumb">
		<div class="agile_inner_breadcrumb">
			<div class="container">
				<ul class="w3_short">
					<li>
						<a href="index.html">Home</a>
						<i>|</i>
					</li>
					<li>Checkout</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- //page -->
	<!-- checkout page -->
	<div class="privacy">
		<div class="container">
			<!-- tittle heading -->
			<h3 class="tittle-w3l">Cart Added
				<span class="heading-style">
					<i></i>
					<i></i>
					<i></i>
				</span>
			</h3>
			<!-- //tittle heading -->
			<div class="checkout-right">
				<h4>Your Cart is added successfully!
					<span></span>
				</h4>
				<div class="table-responsive">
					<span><a href="/">Back to home</a></span>

				</div>
			</div>
		</div>
	</div>
	<!-- //checkout page -->
{% endblock %} {% endcomment %}

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
	<!-- banner-2 -->
	<div class="page-head_agile_info_w3l">

	</div>
	<!-- //banner-2 -->
	<!-- page -->
	<div class="services-breadcrumb">
		<div class="agile_inner_breadcrumb">
			<div class="container">
				<ul class="w3_short">
					<li>
						<a href="index.html">Home</a>
						<i>|</i>
					</li>
					<li>Checkout</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- //page -->
	<!-- checkout page -->
	<div class="privacy">
		<div class="container">
			<!-- tittle heading -->
			<h3 class="tittle-w3l">Checkout
				<span class="heading-style">
					<i></i>
					<i></i>
					<i></i>
				</span>
			</h3>
			<!-- //tittle heading -->
			<div class="checkout-right">
				<h4>Your shopping cart contains:
					<span>{{cart.cartproduct_set.all.count }} Products</span>
				</h4>
				<div class="table-responsive">
					<table class="timetable_sub">
						<thead>
							<tr>
								<th>SL No.</th>
								<th>Product</th>
								<th>Quality</th>
								<th>Product Name</th>

								<th>Rate</th>
								<th>Total</th>
								<th>Remove</th>
							</tr>
						</thead>
						<tbody>
							{% for cp in cart.cartproduct_set.all %}
							<tr class="rem1">
								<td class="invert">{{forloop.counter}}</td>
								<td class="invert-image">
									<a href="single2.html">
										<img src="{{cp.product.image.url}}" alt=" " class="img-responsive">
									</a>
								</td>
								<td class="invert">
									<div class="quantity">
										<div class="quantity-select">
											<div class="entry value-minus">&nbsp;</div>
											<div class="entry value">
												<span>1</span>
											</div>
											<div class="entry value-plus active">&nbsp;</div>
										</div>
									</div>
								</td>
								<td class="invert">{{cp.product.title}}</td>
								<td class="invert">{{cp.product.selling_price}}</td>
								<td class="invert">{{cp.subtotal}}</td>
								<td class="invert">
									<div class="rem">
										<a href="{% url 'ecomapp:namagecart' cp.id %}?action=rmv" class="close1"> </a>
									</div>
								</td>
							</tr>
							{% endfor %}
					<tr style="border:0; text-align: right;"><td colspan="7">Grand Total: Rs. {{cart.total}}</td></tr>
						</tbody>
					</table>
					<center class="p-4" style="margin-top:5px">
						{% if cart.cartproduct_set.all %}
							<a href="{% url 'ecomapp:emptycart' %}" class="btn btn-danger">Empty Cart</a>
						{% endif %}
					</center> 
				</div>
			</div>
			<div class="checkout-left">
				<div class="address_form_agile">
					<h4>Add a new Details</h4>
					<form action="" method="post" class="creditly-card-form agileinfo_form">
						{% csrf_token %}
						<div class="creditly-wrapper wthree, w3_agileits_wrapper">
							<div class="information-wrapper">
								<div class="first-row">
									<div class="controls">
										{{form.ordered_by}}
									</div>
									<div class="w3_agileits_card_number_grids">
										<div class="w3_agileits_card_number_grid_left">
											<div class="controls">
											{{form.shipping_address}}
											</div>
										</div>
										<div class="w3_agileits_card_number_grid_right">
											<div class="controls">
											{{form.mobile}}
											</div>
										</div>
										<div class="clear"> </div>
									</div>
									<div class="controls">
										{{form.email}}
									</div>
									<div class="controls">
										{{form.payment_method}}
									</div>
								</div>
								<button type="submit" class="submit check_out">Delivery to this Address</button>
							</div>
						</div>
					</form>
					<div class="checkout-right-basket">
						<a href="payment.html">Make a Payment
							<span class="fa fa-hand-o-right" aria-hidden="true"></span>
						</a>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //checkout page -->
{% endblock %}

templates/customerprofile.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
	<!-- banner-2 -->
	<div class="page-head_agile_info_w3l">

	</div>
	<!-- //banner-2 -->
	<div class="services-breadcrumb">
		<div class="agile_inner_breadcrumb">
			<div class="container">
				<ul class="w3_short">
					<li>
						<a href="/">Home</a>
						<i>|</i>
					</li>
					<li>Profile</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="privacy">
		<div class="container">
				<div class="grid_3 grid_5 wthree">
					<div class="col-md-5 agileits-w3layouts">
						<h3>Your Detail Information</h3>
						<div class="tab-pane active" id="domprogress">
							<p><b>Name : </b>{{customer.full_name}}</p>
							<p><b>User Name : </b>{{customer.user.username}}</p>
							<p><b>Address : </b>{{customer.address}}</p>
							<p><b>Joined Date: </b>{{customer.joined_on|date}}</p>
						</div>
					</div>
				</div>
				<b>Previous Orders</b>
				<div class="col-md-7 w3-agileits">
					<div class="bs-docs-example">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>S.N.</th>
							<th>Order ID</th>
							<th>Total Amount</th>
							<th>Order Date</th>
							<th>Order Status</th>
						</tr>
					</thead>
					<tbody>
						{% for order in orders %}
						<tr>
							<td >{{forloop.counter}}</td>
							<td><a href="{% url 'ecomapp:customerorderdetail' order.id %}">order_{{order.id}}</a></td>
							<td>{{order.total}}</td>
							<td>{{order.created_at|timesince}} ago</td>
							<td>{{order.order_status}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>

				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
{% endblock %}

templates/customerregistration.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

	<!-- banner-2 -->
	<div class="page-head_agile_info_w3l">

	</div>
	<!-- //banner-2 -->
	<!-- page -->
	<div class="services-breadcrumb">
		<div class="agile_inner_breadcrumb">
			<div class="container">
				<ul class="w3_short">
					<li>
						<a href="index.html">Home</a>
						<i>|</i>
					</li>
					<li>Customer Registration</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- //page -->
	<!-- checkout page -->
	<div class="privacy">
		<div class="container">
			<!-- tittle heading -->
			<h3 class="tittle-w3l">Customer Registration
				<span class="heading-style">
					<i></i>
					<i></i>
					<i></i>
				</span>
			</h3>
			<!-- //tittle heading -->
					<div class="checkout-left">
				<div class="address_form_agile contact-form wthree">
					<h4 style="margin-bottom:0">Add a new Details</h4>
					<hr>
					<form action="" method="post" class="creditly-card-form agileinfo_form">
						{% csrf_token %}
						<div class="creditly-wrapper wthree, w3_agileits_wrapper">
							<div class="information-wrapper">
								<div class="first-row">
									<div class="w3_agileits_card_number_grids">
										<b>Email</b>
										<div class="w3_agileits_card_number_grid_right">
											<div class="controls">
												{{form.email}}
											</div>
										</div>
										<div class="w3_agileits_card_number_grid_left">
											<b>Password</b>
											<div class="controls">
												{{form.password}}
											</div>
										</div>
										<div class="clear"> </div>
									</div>
									<b>Full Name</b>
									<div class="controls">
										{{form.full_name}}
									</div>
									<b>Mobile</b>
									<div class="controls">
										{{form.mobile 	}}
									</div>
									<b>Address</b>
									<div class="controls">
										{{form.address}}
									</div>
								</div>
								<button class="submit check_out">Register as a Customer</button>
							</div>
						</div>
					</form>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //checkout page -->
	<script type="text/javascript">

	</script>

{% endblock %}

templates/khaltirequest.html
<html>
<head>
    <script src="https://khalti.s3.ap-south-1.amazonaws.com/KPG/dist/2020.12.17.0.0.0/khalti-checkout.iffe.js"></script>
</head>
<body>
    ...
    <!-- Place this where you need payment button -->
    <button id="payment-button">Pay with Khalti</button>
    <!-- Place this where you need payment button -->
    <!-- Paste this code anywhere in you body tag -->
    <script>
        var config = {
            // replace the publicKey with yours
            "publicKey": "test_public_key_dc74e0fd57cb46cd93832aee0a390234",
            "productIdentity": "1234567890",
            "productName": "Dragon",
            "productUrl": "http://gameofthrones.wikia.com/wiki/Dragons",
            "paymentPreference": [
                "KHALTI",
                "EBANKING",
                "MOBILE_BANKING",
                "CONNECT_IPS",
                "SCT",
                ],
            "eventHandler": {
                onSuccess (payload) {
                    // hit merchant api for initiating verfication
                    console.log(payload);
                },
                onError (error) {
                    console.log(error);
                },
                onClose () {
                    console.log('widget is closing');
                }
            }
        };

        var checkout = new KhaltiCheckout(config);
        var btn = document.getElementById("payment-button");
        btn.onclick = function () {
            // minimum transaction amount must be 10, i.e 1000 in paisa.
            checkout.show({amount: 1000});
        }
    </script>
    <!-- Paste this code anywhere in you body tag -->
    ...
</body>
</html>

templates/mycart.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
	/* Chrome, Safari, Edge, Opera */
	input::-webkit-outer-spin-button,
	input::-webkit-inner-spin-button {
	-webkit-appearance: none;
	margin: 0;
	}

	/* Firefox */
	input[type=number] {
	-moz-appearance: textfield;
	}

    input {
		border : #E5E5E5;
        resize: horizontal;
        width: 36px;
    }


</style>  
{% endblock %}
{% block main %}
	<!-- banner-2 -->
	<div class="page-head_agile_info_w3l">

	</div>
	<!-- //banner-2 -->
	<!-- page -->
	<div class="services-breadcrumb">
		<div class="agile_inner_breadcrumb">
			<div class="container">
				<ul class="w3_short">
					<li>
						<a href="index.html">Home</a>
						<i>|</i>
					</li>
					<li>My Cart</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- //page -->
	<!-- checkout page -->
	<div class="privacy">
		<div class="container">
			<!-- tittle heading -->
			<h3 class="tittle-w3l">My Cart
				<span class="heading-style">
					<i></i>
					<i></i>
					<i></i>
				</span>
			</h3>
			<!-- //tittle heading -->
			<div class="checkout-right">
				<h4>Your shopping cart contains:
					<span>{{cart.cartproduct_set.all.count }} Products</span>
				</h4>
				<div class="table-responsive">
					<table class="timetable_sub">
						<thead>
							<tr>
								<th>SL No.</th>
								<th>Product</th>
								<th>Quality</th>
								<th>Product Name</th>

								<th>Rate</th>
								<th>Total</th>
								<th>Remove</th>
							</tr>
						</thead>
						<tbody>
							{% for cp in cart.cartproduct_set.all %}
							<tr class="rem1">
								<td class="invert">{{forloop.counter}}</td>
								<td class="invert-image">
									<a href="single2.html">
										<img src="{{cp.product.image.url}}" alt=" " class="img-responsive">
									</a>
								</td>
								<td class="invert">
									<div class="quantity">
										<div class="quantity-select">
											<div class="entry value-minus" data-pid="{{ cp.id }}" data-url="{% url 'ecomapp:namagecart' cp.id %}">&nbsp;</div>
											<div class="entry value">
												<span>{{ cp.quantity }}</span>
											</div>
											<div class="entry value-plus active" data-pid="{{ cp.id }}" data-url="{% url 'ecomapp:namagecart' cp.id %}">&nbsp;</div>
										</div>
									</div>
								</td>
								<td class="invert">{{cp.product.title}}</td>
								<td class="invert">{{cp.product.selling_price}}</td>
								<td class="invert subtotal">{{cp.subtotal}}</td>
								<td class="invert">
									<div class="rem">
										<a href="{% url 'ecomapp:namagecart' cp.id %}?action=rmv" class="close1"> </a>
									</div>
								</td>
							</tr>
							{% endfor %}
							<tr style="border:0; text-align: right;">
								<td colspan="7" class="total">Grand Total: Rs. {{cart.total}}</td>
							</tr>
						</tbody>
					</table>
					<center class="p-4" style="margin-top:5px">
						{% if cart.cartproduct_set.all %}
							<a href="{% url 'ecomapp:emptycart' %}" class="btn btn-danger">Empty Cart</a>
							<a href="{% url 'ecomapp:checkout' %}" class="btn btn-primary">Checkout</a>
						{% endif %}
					</center> 
				</div>
			</div>
		</div>
	</div>
	<!-- //checkout page -->
{% endblock %}
{% block script %}

<script>
	$('.value-plus').on('click', function () {
		var divUpd = $(this).parent().find('.value'),
			newVal = parseInt(divUpd.text(), 10) + 1;
		divUpd.text(newVal);
		var p_id = $(this).data('pid')
		var url = $(this).data('url')
		console.log(p_id + url)
		$.ajax({
			url : url,
			method : 'GET',
			data : {
				'quantity' : newVal,
				'product_id' : p_id
			},
			success : function(data){
				$('.product-quantity').html(data.quantity)
				$('.total').html(data.total)
				$('.subtotal').html(data.subtotal)
			}
		})
	});

	$('.value-minus').on('click', function () {
		var divUpd = $(this).parent().find('.value'),
			newVal = parseInt(divUpd.text(), 10) - 1;
		if (newVal >= 1) divUpd.text(newVal);

		var p_id = $(this).data('pid')
		var url = $(this).data('url')
		console.log(p_id + url)
		$.ajax({
			url : url,
			method : 'GET',
			data : {
				'quantity' : newVal,
				'product_id' : p_id
			},
			success : function(data){
				console.log(data.total)
				$('.total').html(data.total)
				$('.subtotal').html(data.subtotal)
			}
		})
	});
</script>
{% endblock %}

templates/productreview.html
{% load static %}
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
        <h2 id="fh2">WE APPRECIATE YOUR REVIEW!</h2>
<h6 id="fh6">Your review will help us to improve our quality products, and customer services.</h6>


<form id="feedback" action="{% url 'ecomapp:product-review' product.id %}" method="POST">
    {% csrf_token %}

 <div class="pinfo">Rate our overall services.</div>
<div class="form-group">
    <div class="rating-container rating-md rating-animate">
        <div class="rating-stars">
            <span onclick="rating(1)" class="fa fa-star-o" data-rating="1"></span>
            <span onclick="rating(2)" class="fa fa-star-o" data-rating="2"></span>
            <span onclick="rating(3)" class="fa fa-star-o" data-rating="3"></span>
            <span onclick="rating(4)" class="fa fa-star-o" data-rating="4"></span>
            <span onclick="rating(5)" class="fa fa-star-o" data-rating="5"></span>
            <input type="hidden" name="star" id="starid" class="rating-value" value="0" >
        </div>
        <div  class="caption"><span id="rated_lebel" class="label label-default">Not </span> Rated</div>
    </div>
</div>

 <div class="pinfo">Write your feedback.</div>
  

<div class="form-group">
  <div class="col-md-12 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
  <textarea name="review" class="form-control" id="review" rows="3"></textarea>
 
    </div>
  </div>
</div>

 <button type="submit" class="btn btn-primary">Submit</button>
 
</form>
</div>
    <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>





<!-- Star rating -->
<script>
	function rating(starnum){
		document.getElementById("rated_lebel").innerHTML = starnum;
	}

var $star_ratings = $('.rating-stars .fa');
var SetStarRatings = function(){
	return $star_ratings.each(function(){
		if (parseInt($star_ratings.siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))){
			return $(this).removeClass('fa-star-o').addClass('fa-star-o');

		} else {
			return $(this).removeClass('fa-star').addClass('fa-star-o');

		}
	});
};
$star_ratings.on('click', function(){
	$star_ratings.siblings('input.rating-value').val($(this).data(rating));
	return SetStarRatings();
});
</script>